# ---- Tile codes ----
EMPTY = 0
WALL = 5
DOOR_LOCKED = 10
DOOR_LOCKED_HOT = 15
DOOR_LOCKED_COLD = 17
DOOR_UNLOCKED = 20
DOOR_OPEN = 22
DOOR_UNLOCKED_HOT = 25
DOOR_UNLOCKED_COLD = 27
CUPBOARD_LOCKED = 30
CUPBOARD_UNLOCKED = 40
CUPBOARD_UNLOCKED_KEYCARD = 50
KEY_TILE = 60  # keys are placed "on" open tiles; this tile is passable
PERSON_TILE = 70
EXIT = 80
FIRE = 90
UNKNOWN = 255

# ---- Actions ----
FORWARD = 0
ROT_LEFT = 1
ROT_RIGHT = 2
PICK_KEY = 3
UNLOCK_CUPBOARD = 4
PICK_KEYCARD = 5
UNLOCK_DOOR = 6
TALK_PERSON = 7
CHECK_DOOR_TEMP = 8
OPEN_DOOR = 9

# ---- Directions ----
NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3

forward_offset = {
    NORTH: (-1, 0),
    EAST: (0, 1),
    SOUTH: (1, 0),
    WEST: (0, -1)
}
